FROM python:3.12-slim

RUN pip install --no-cache-dir mlflow==3.12.0 boto3 psycopg2-binary

EXPOSE 5000

CMD ["mlflow", "server", \
     "--host", "0.0.0.0", \
     "--port", "5000", \
     "--backend-store-uri", "sqlite:///mlruns/mlflow.db", \
     "--default-artifact-root", "/mlruns/artifacts"]
